DEFAULT_VENDOR_ID = 0x0483
DEFAULT_PRODUCT_ID = 0x5840

TICKERS = {
    "NIFTY": "^NSEI",
    "SENSX": "^BSESN",
    "BANK": "^NSEBANK",
    "N50": "NIFTYBEES.NS",
    "BANK": "BANKBEES.NS",
    "IT": "ITBEES.NS",
    "PHAR": "PHARMABEES.NS",
    "AUTO": "AUTOBEES.NS",
    "CPSE": "CPSEETF.NS",
    "PSUB": "PSUBNKBEES.NS",
    "INFR": "INFRABEES.NS",
    "GOLD": "GOLDBEES.NS",
    "HANG": "HNGSNGBEES.NS",

    # "ITC": "ITC.NS",
    # "JUB": "JUBLFOOD.NS",
    # "JKP": "JKPAPER.NS",
    # "JAI": "JISLJALEQS.NS",
    # "HNG": "HNGSNGBEES.NS",

    # "N50": "NIFTYBEES.NS",
    # "PVR": "PVRINOX.NS",
    # "APLH": "APOLLOHOSP.NS",
    # "APLT": "APOLLOTYRE.NS",
    # "BATA": "BATAINDIA.NS",
    # "RIL": "RELIANCE.NS",
    # "RAY": "RAYMOND.NS",
    # "ITCH": "ITCHOTELS.NS",
    # "NEST": "NESTLEIND.NS",
    # "PAY": "PAYTM.NS",
    # "FORT": "FORTIS.NS",
    # "PFZ": "PFIZER.NS",
    # "CIP": "CIPLA.NS",
    # "IRCT": "IRCTC.NS",
    # "TCS": "TCS.NS",
    # "INFY": "INFY.NS",
    # "TSTL": "TATASTEEL.NS",
    # "GOLD": "GOLDBEES.NS",
    # "IOC": "IOC.NS",
    # "MAX": "MAXHEALTH.NS",
    # "JIOFN": "JIOFIN.NS",
    # "MOTR": "TMCV.NS",
    # "OIL": "OIL.NS",

}
